
image:
  file: .gitpod.Dockerfile
tasks:
  - init: echo 'PATH_add ~/julia-1.8.0/bin' > /workspace/.envrc  \
      && echo 'export SEARCHLIGHT_USERNAME="gitpod"' >> /workspace/.envrc 
  - command: python3 -m http.server 8080 -d docs/build
  - command: gp preview $(gp url 8080)
  - command: julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate();include("testsCreateContract.jl"); include("testPendingMutations.jl")'
