image:
  file: .gitpod.Dockerfile

tasks:
  - name: Script Task
    init: >
      echo 'init script' 
      && echo 'export SEARCHLIGHT_USERNAME="gitpod"' > $GITPOD_REPO_ROOT/.envrc 
      && direnv allow $GITPOD_REPO_ROOT
  - command: python3 -m http.server 8080 -d docs/build
  - command: julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate();include("testCreateContract.jl"); include("testPendingMutations.jl")'

  # - command: python3 -m http.server 8080 -d docs/build
  - command: gp open test.ipynb

