image:
  file: .gitpod.Dockerfile
tasks:
  - init: cd .. &&
      echo 'PATH_add /home/gitpod/julia-1.6.5/bin' > .envrc
  - command: python3 -m http.server 8080 -d docs/build
  - command: gp preview $(gp url 8080)
  - command: cat db/connectionGITPOD.yml >db/connection.yml
