name: CI
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - "releases/**"
jobs:
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ vars.JULIA_MINOR_VERSION }}
      - run: export SEARCHLIGHT_USERNAME="postgres"; export SEARCHLIGHT_PASSWORD="postgres"; GENIE_ENV="test" julia --project=$(pwd) -e'push!(LOAD_PATH,"src"); using Pkg; Pkg.instantiate();include("test/runtests.jl")'
        shell: bash
